version: "2.1"
services:
  mssql:
    container_name: guest_book_fullstack_db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "GuestBook42Pass"

  app:
    container_name: guest_book_fullstack_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:443"
      - "5000:80"
    depends_on:
      mssql:
        condition: service_started
    